### ISSUE TITLE
output_api should use CRLF

### ISSUE THREAD

**Issue by thomas-joiner** [Nerdmaster/ruby-irc-yail#1]
According to the documentation, puts will end everything with a "record separator usually a LF".

However, according to RFC1459:

"IRC messages are always lines of characters terminated with a CR-LF (Carriage Return - Line Feed) pair, and these messages shall not exceed 512 characters in length, counting all characters including the trailing CR-LF."

As such the definition for raw should be something like:

def raw(line, report = true)
  @socket.send "#{line}\r\n", 0
  report "bot: #{line.inspect}" if report
end

(Note that one could also use @socket.write, I just used send).

I found this out because the server I was trying to connect to claimed that I was not sending it a password, despite the fact that I could see it was sending it.  At first I thought it was some sort of timing issue, due to the fact that once I put the password send right after the socket creation it worked, but it turned out that I had just ended the command with CRLF because that's what I'm used to doing with text protocols.  Thankfully I noticed what it was before I  submitted a bug report for the server password not working properly.

I'm not sure if most servers will accept both LF and CRLF as a line ending.  However, the particular server I was connecting to didn't.  (The server is one of justin.tv's IRC servers for the record).

I've forked it and will perform a pull request.

**Comment by Nerdmaster** [comment]
Nice catch, I'll try to get this dealt with today.

**Comment by Nerdmaster** [comment]
I'm going to modify this a bit - the tests caught a "bug" (if you can call it that) because I mock `puts`, not `send`.  `send` is pretty specific to the TCP Socket, so to keep things in line with my "you can use any IO object" stance, I'm going to convert this code to use a `puts`.

I tested in IRB and when you enter something like `puts "foo\r\n"`, you end up with just a single \r\n at the end of the line, so puts does seem smart enough to know that if you give it a newline, it won't throw out its own.  However, please let me know if, after I commit this, it doesn't work for you.

**Comment by Nerdmaster** [comment]
Committed - seems to work in a simple test case, let me know if you see other issues.

**Comment by thomas-joiner** [comment]
Just tested out the modifications and they worked for me.  Thanks.

**Comment by Nerdmaster** [comment]
Heh, logged in as my work user - oops.  Deleted response, but it was:

Thanks for finding the bug in the first place - I would never have caught this! And thanks for the quick test, too.

**Comment by thomas-joiner** [comment]
No problem.

I'm just glad that when I ran into a server that didn't work that I was able to figure out why it wasn't accepting the messages.
