### ISSUE TITLE
What can i do for issueing `WHOIS' to server.

### ISSUE THREAD

**Issue by takano32** [Nerdmaster/ruby-irc-yail#6]
i use create_command and get below result.

```
`legacy_process_event': Unknown outgoing event: #<Net::YAIL::OutgoingEvent [whois]:0x00000000eb6680> (RuntimeError)
```

something wrong w/ my define?

```
@irc.create_command :whois,  "WHOIS :nick", :nick
```

Thank you.

**Comment by Nerdmaster** [comment]
I'll take a look at this today or tonight and get back to you.  At first glance it seems like that should work, but I tend to forget YAIL code pretty quickly when I'm not burying myself in it regularly.

**Comment by Nerdmaster** [comment]
Try pulling from master and let me know if what I changed fixes the issue.  As far as I can tell, it should, because I was blindly crashing any time anything unknown went out, based on my original legacy system which didn't allow as much customization, particularly on outgoing messages.

Also, if you've had to define any other outgoing messages, please share them with me and I'll add them to the core system if they make sense.  There are a lot of outgoing messages I haven't bothered making into methods but probably should.

**Comment by takano32** [comment]
Thanks a lot for your agile hack.
Ill try pull and issue WHOIS this afternoon. :-)

Thanks!

**Comment by takano32** [comment]
your patch well works!

i define WHOIS

```
@irc.create_command :whois,  "WHOIS :nick", :nick
```

and i can receive WHOIS response.

```
@irc.hearing_whoisuser do |event|
    nick, name = event.message.split ' '
    # name is login name!!!
end
```

Thank you!

**Comment by Nerdmaster** [comment]
Glad to hear it!  I'll get a WHOIS command built in when I get some time.  It looks like the spec defines WHOIS as a rather odd command with an optional parameter for a "target".  I won't be able to just use `create_command` because that optional parameter is the **first** parameter when it's there.  In other words, you can do this:

`WHOIS [nick]`

or this:

`WHOIS [target] [nick]`

Anyway, I'll try to build a command that works just like yours but also allows the optional target as well.
